### ISSUE TITLE
Change license to MIT from MPL

### ISSUE THREAD

**Issue by Revimal** [openndr/ndr-build-env#27]
Literally

**Comment by Dry8r3aD** [comment]
jup jup

**Comment by Revimal** [comment]
1. make LICENSE-MIT file
2. then, copy&paste MIT license texts into LICENSE-MIT file (example: https://github.com/Revimal/ndrte/blob/master/LICENSE-MIT)
3. change original LICENSE file (like this: https://github.com/Revimal/ndrte/blob/master/LICENSE)

thx for your contribution :)
